eval_interval: 50
common:
  device: 'cuda:0' # 'cuda:0' or 'cpu'

# --- OPQ 模型配置 ---
opq:
  # 模型架构参数
  model_params:

    n_codebook: 32
    codebook_size: 256
    opq_use_gpu: False
    opq_gpu_id: 0
    faiss_omp_num_threads: 4

    test_size: 0.05
    random_state: 42
