# configs/opq.yaml (統一後的版本)

common:
  device: 'cuda:0'
  eval_interval: 50

# --- OPQ 模型配置 ---
opq:
  model_params:
    num_levels: 32          
    codebook_size: 256
    opq_use_gpu: True
    opq_gpu_id: 0
    faiss_omp_num_threads: 4
    test_size: 0.05
    random_state: 42
    has_dup_layer: false