defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  # - rich_progress_bar # does not work well with unbonunded datasets.
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "checkpoint_{epoch:03d}_{step:06d}"
  monitor: "val/loss"
  mode: "min"
  auto_insert_metric_name: False
  every_n_train_steps: 5000

early_stopping:
  monitor: "val/loss"
  patience: 100
  mode: "min"

model_summary:
  max_depth: -1
